HelloTickets/HelloTickets/Models/DataControl/EventViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HelloTickets.Models.DataControl
{
    public class EventViewModel
    {
        public int Id { get; set; }
        [Required]
        [Remote(action: "VerifyEvent", controller: "Validation")]
        [Display(Name = "NameValue", ResourceType = typeof(Resources.Anotation))]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Date", ResourceType = typeof(Resources.Anotation))]
        public DateTime Date { get; set; }
        [Required]
        [Display(Name = "Banner", ResourceType = typeof(Resources.Anotation))]
        public string Banner { get; set; }
        [Required]
        [Display(Name = "Description", ResourceType = typeof(Resources.Anotation))]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Venue", ResourceType = typeof(Resources.Anotation))]
        public int VenueId { get; set; }

        public IEnumerable<SelectListItem> Venues { get; set; }
    }
}

HelloTickets/HelloTickets/Models/Home/ATicketsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloTickets.Models.Home
{
    public class ATicketsViewModel
    {
        public IEnumerable<TicketsViewModel> Tickets { get; set; }

        public bool confirmation { get; set; }
    }
}

HelloTickets/HelloTickets/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HelloTickets.Data;
using HelloTickets.Models.DataControl;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;

namespace HelloTickets.Controllers
{
    public class EventController : Controller
    {
        private EventDataLayer _edata;
        private VenueDataLayer _vdata;
        private IHostingEnvironment AppEnvironment;

        public EventController(EventDataLayer edata, 
            VenueDataLayer vdata,
            IHostingEnvironment appEnvironment)
        {
            _edata = edata;
            _vdata = vdata;
            AppEnvironment = appEnvironment;
        }

        #region Event
        [HttpGet]
        public IActionResult AddEvent()
        {
            EventViewModel model = new EventViewModel();
            model.Date = DateTime.Now;
            model.Venues = _vdata.GetVenueListItem();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddEvent(IFormFile uFile, EventViewModel model)
        {
            if (uFile == null)
            {
                return View(model);
            }

            string path = "/images/" + uFile.FileName;
            using (var fileStream = new FileStream(AppEnvironment.WebRootPath + path, FileMode.Create))
            {
                await uFile.CopyToAsync(fileStream);
            }
            model.Banner = path;
            _edata.AddEvent(model.Name, model.Date, model.Banner, model.Description, model.VenueId);
            var location = new Uri($"{Request.Scheme}://{Request.Host}/DataControl/DataList#three");
            return Redirect(location.ToString());
        }

        [HttpGet]
        public IActionResult EditEvent(int id)
        {
            EventViewModel model = new EventViewModel();
            var res = _edata.GetEventById(id, true);
            model.Name = res.Name;
            model.Banner = res.Banner;
            model.Date = res.Date;
            model.Description = res.Description;
            model.Id = res.Id;
            model.VenueId = res.VenueId;
            model.Venues = _vdata.GetVenueListItem();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditEvent(int id, IFormFile uFile, string LastBanner, EventViewModel model)
        {
            if (uFile != null)
            {
                string path = "/images/" + uFile.FileName;
                using (var fileStream = new FileStream(AppEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uFile.CopyToAsync(fileStream);
                }
                model.Banner = path;
            }
            else
            {
                model.Banner = LastBanner;
            }

            _edata.UpdateEvent(id, model.Name, model.Date, model.Banner, model.Description, model.VenueId);
            var location = new Uri($"{Request.Scheme}://{Request.Host}/DataControl/DataList#three");
            return Redirect(location.ToString());
        }

        public IActionResult RemoveEvent(int id)
        {
            _edata.RemoveEvent(id);
            var location = new Uri($"{Request.Scheme}://{Request.Host}/DataControl/DataList#three");
            return Redirect(location.ToString());
        }
        #endregion
    }
}

HelloTickets/HelloTickets/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Http;
using HelloTickets.Models.DataTemplate;
using HelloTickets.Models.Home;
using HelloTickets.Models;
using HelloTickets.Data;
using System.Security.Claims;

namespace HelloTickets.Controllers
{
    public class HomeController : Controller
    {
        private CityDataLayer _cdata;
        private VenueDataLayer _vdata;
        private EventDataLayer _edata;
        private TicketDataLayer _tdata;
        private OrderDataLayer _odata;
        private UserDataLayer _udata;

        public HomeController(
            CityDataLayer cdata, 
            VenueDataLayer vdata, 
            EventDataLayer edata, 
            TicketDataLayer tdata,
            OrderDataLayer odata,
            UserDataLayer udata)
        {
            _cdata = cdata;
            _vdata = vdata;
            _edata = edata;
            _tdata = tdata;
            _odata = odata;
            _udata = udata;
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

        public async Task<IActionResult> Index()
        {
            string uname = User.Identity.Name;
            IndexViewModel model = new IndexViewModel();
            model.TopEvents = await _edata.GetEventsTakeAsync(3);

            model.TopTickets = await _tdata.GetTicketsTakeAsync(3);
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Events()
        {
            IEnumerable<Event> events = await _edata.GetAllEventsAsync();
            return View(events);
        }

        public async Task<IActionResult> Tickets(int ID, bool conf)
        {
            ATicketsViewModel model = new ATicketsViewModel();
            List<TicketsViewModel> tickets = new List<TicketsViewModel>(1);
            if (ID != 0)
            {
                var res = await _tdata.GetTicketsByEventAsync(ID);
                foreach (Ticket t in res)
                {
                    TicketsViewModel tvm = new TicketsViewModel(t);
                    tvm.IsValid = await _odata.ExistTicketAndBuyerFromOrder(t.Id, t.SellerId);
                    tickets.Add(tvm);
                };
                var resName = await _edata.GetEventByIdAsync(ID);
                ViewData["NameEvents"] = resName.Name;
            }
            else
            {
                var res = await _tdata.GetAllTicketsAsync();
                foreach (Ticket t in res)
                {
                    TicketsViewModel tvm = new TicketsViewModel(t);
                    tvm.IsValid = await _odata.ExistTicketAndBuyerFromOrder(t.Id, t.SellerId);
                    tickets.Add(tvm);
                };
            }
            model.confirmation = conf;
            model.Tickets = tickets;
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> MyTickets()
        {
            string userId = User.Claims.First((x) => x.Type == ClaimTypes.NameIdentifier).Value;
            MyTicketsViewModel model = new MyTicketsViewModel();
            model.Selling = await _tdata.GetTicketsByUserAsync(userId);

            var res = await _odata.GetStatusTicketsByUserAsync(userId, OrderStatus.WaitingForConfirmation);
            model.WaitingConfirmation = Convert(res);

            var res1 = await _odata.GetStatusTicketsByUserAsync(userId, OrderStatus.Confirmed);
            model.Sold = Convert(res1);
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> MyOrders()
        {
            IEnumerable<Order> model = await _odata.GetOrderByUserAsync(User.Claims.First((x) => x.Type == ClaimTypes.NameIdentifier).Value);
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> UserInfo()
        {
            User u = await _udata.GetUserByIdAsync(User.Claims.First((x) => x.Type == ClaimTypes.NameIdentifier).Value);
            UserInfoViewModel model = new UserInfoViewModel();
            model.FirstName = u.FirstName;
            model.LastName = u.LastName;
            model.Localization = u.Localization;
            model.Email = u.Email;
            model.Adress = u.Address;
            model.PhoneNomber = u.PhoneNumber;
            return View(model);
        }


        private IEnumerable<TicketOrderViewModel> Convert(IEnumerable<Order> main)
        {
            string userId = User.Claims.First((x) => x.Type == ClaimTypes.NameIdentifier).Value;
            List<TicketOrderViewModel> list = new List<TicketOrderViewModel>();
            foreach(Order o in main.ToList())
            {
                TicketOrderViewModel item = new TicketOrderViewModel(o.Ticket);
                item.OrderId = o.Id;
                list.Add(item);
            }
            return list;
        }
    }
}

HelloTickets/HelloTickets/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HelloTickets.Data;
using HelloTickets.Models.Home;
using HelloTickets.Models.DataTemplate;
using System.Security.Claims;

namespace HelloTickets.Controllers
{
    public class TicketController : Controller
    {
        private TicketDataLayer _tdata;
        private EventDataLayer _edata;

        public TicketController(TicketDataLayer tdata, EventDataLayer edata)
        {
            _tdata = tdata;
            _edata = edata;
        }

        #region Ticket
        [HttpGet]
        public IActionResult AddTicket()
        {
            AddTicketViewModel model = new AddTicketViewModel();
            model.Events = _edata.GetEventsListItem();
            return View(model);
        }

        [HttpPost]
        public IActionResult AddTicket(AddTicketViewModel model)
        {
            if (ModelState.IsValid)
            {
                string userId = User.Claims.First((x) => x.Type == ClaimTypes.NameIdentifier).Value;
                _tdata.AddTicket(new Ticket { EventId = model.EventId, Price = model.Price, SellerId = userId });
                return RedirectToAction("Tickets", "Home");
            }
            else
            {
                model.Events = _edata.GetEventsListItem();
                return View(model);
            }
        }
        #endregion
    }
}

HelloTickets/HelloTickets/Controllers/TradeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HelloTickets.Data;
using System.Security.Claims;

namespace HelloTickets.Controllers
{
    public class TradeController : Controller
    {
        private OrderDataLayer _odata;

        public TradeController(OrderDataLayer odata)
        {
            _odata = odata;
        }

        #region buy
        public async Task<IActionResult> Buy(int ticketID)
        {
            string userId = User.Claims.First((x) => x.Type == ClaimTypes.NameIdentifier).Value;
            bool res = await _odata.AddOrderByTicketId(ticketID, userId);
            return RedirectToAction("Tickets", "Home", new { conf = true });
        }

        public async Task<IActionResult> Confirmation(bool status, int Id)
        {
            if (status)
                await _odata.UpdateStatusOrder(Id, OrderStatus.Confirmed);
            else
                await _odata.UpdateStatusOrder(Id, OrderStatus.Rejected);

            var location = new Uri($"{Request.Scheme}://{Request.Host}/Home/MyTickets#two");
            return Redirect(location.ToString());
        }
        #endregion
    }
}

HelloTickets/HelloTickets/Controllers/UserController.cs
using HelloTickets.Data;
using HelloTickets.Models.DataTemplate;
using HelloTickets.Models.Home;
using HelloTickets.Models.Manage;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloTickets.Controllers
{
    [Authorize]
    public class UserController: Controller
    {
        private UserDataLayer _udata;
        private RoleDataLayer _rdata;
        private readonly SignInManager<User> SignInManager;

        public UserController(
            UserDataLayer udata,
            RoleDataLayer rdata,
            SignInManager<User> signInManager)
        {
            _udata = udata;
            _rdata = rdata;
            SignInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Users()
        {
            List<UserListViewModel> model = new List<UserListViewModel>();
            var us = _udata.GetUsers();
            model = us.Select(u => new UserListViewModel
                                        {
                                            Id = u.Id,
                                            Name = u.UserName,
                                            Email = u.Email,
                                            RoleName = _rdata.GetFirstRoleNameByUser(u)
                                        }).Where((X) => X.RoleName != "super").ToList();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string idUser)
        {
            User u = await _udata.GetUserByIdAsync(idUser);
            UserViewModel model = new UserViewModel()
                                        {
                                            Email = u.Email,
                                            Id = idUser,
                                            Name = u.UserName,
                                            RoleId = _rdata.GetRoleIdToUser(u),
                                            Roles = _rdata.GetAllRoles()
                                        };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditUser(string idUser, UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Id = idUser;
                var result = _udata.UpdateUserAsync(model);
                if(result.Result.Succeeded)
                    return RedirectToAction("Users");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditCurrentUser()
        {
            User u = await _udata.GetUserByNameAsync(User.Identity.Name);
            UserInfoViewModel model = new UserInfoViewModel();
            model.Id = u.Id;
            model.FirstName = u.FirstName;
            model.Email = u.Email;
            model.Localization = u.Localization;
            model.LastName = u.LastName;
            model.Adress = u.Address;
            model.PhoneNomber = u.PhoneNumber;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCurrentUser(string id, UserInfoViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Id = id;
                var result = _udata.UpdateCurrentUserAsync(model);
                if (result.Result.Succeeded)
                {
                    User u = await _udata.GetUserByIdAsync(model.Id);
                    await SignInManager.RefreshSignInAsync(u);
                    Response.Cookies.Append(
                        CookieRequestCultureProvider.DefaultCookieName,
                        CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(model.Localization)),
                        new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
);
                    return RedirectToAction(nameof(HomeController.UserInfo), "Home");
                }

                return View(model);
            }

            return View(model);
        }
    }
}

HelloTickets/HelloTickets/Views/Home/Events.cshtml
@using HelloTickets.Models.DataTemplate
@inject IViewLocalizer loc
@model IEnumerable<Event>
@{
    ViewData["Title"] = loc["Title"];
}

<div id="main" class="wrapper style1">
    <div class="container">
        <header class="major">
            <h2>@loc["Events"]</h2>
        </header>
        <div class="box alt">
            <div class="row uniform">
                @foreach (Event ev in Model)
                {
                    <section class="4u 6u(medium) 12u$(xsmall)">
                        <h4><a asp-area="" asp-route-id="@ev.Id" asp-controller="Home" asp-action="Tickets">@ev.Name</a></h4>
                        <p>@ev.Venue.City.Name  @ev.Venue.Address</p>
                        <img width="170" height="170" src="@Url.Content(@ev.Banner)" alt="" class="alt major fa-area-chart" />
                        <p>@loc["Date"] @ev.Date.ToString("dd.MM.yyyyг.")</p>
                    </section>
                }
                </div>
            </div>
        </div>
    </div>

HelloTickets/HelloTickets/Views/Home/GlobalMap.cshtml
@using HelloTickets.Models.DataTemplate
@using HelloTickets.Models.Home;
@inject IViewLocalizer loc
@model IndexViewModel
@{
    ViewData["Title"] = loc["Title"];
}
<div class="acontent">
    <header class="major">
        <span class="image main"><img src="~/images/Bmap.png" /></span>
        <h2>@loc["Velcome"]</h2>
        <p>@loc["VelcomeDescription"]</p>
    </header>
</div>

HelloTickets/HelloTickets/Views/Home/Index.cshtml
@using HelloTickets.Models.DataTemplate
@using HelloTickets.Models.Home;
@inject IViewLocalizer loc
@model IndexViewModel
@{
    ViewData["Title"] = loc["Title"];
}

    <section id="one" >
        <div class="content">
            <header class="major">
                <h2>@loc["Velcome"]</h2>
                <p>@loc["VelcomeDescription"]</p>
                <img src="~/images/Banner.png" alt="" />
            </header>
        </div>
        @*@await Html.PartialAsync("GlobalMap")*@
        <h3><a href="#two" class="goto-next scrolly"></a></h3>
    </section>

    <section id="two" class="spotlight style1 bottom">
        <span class="image fit main"><img src="images/background.jpg" alt="" /></span>
        <div class="content">
            <header >
                <h3>@loc["Events"]</h3>
                <p>@loc["EventsDescription"]</p>
                <hr />
            </header>
            <div class="box alt">
                <div class="row uniform">
                    @foreach (Event ev in Model.TopEvents)
                    {
                        <section class="4u 6u(medium) 12u$(xsmall)">
                            <header>
                                <h3>
                                    <a asp-area="" asp-route-id="@ev.Id" asp-controller="Home" asp-action="Tickets">@ev.Name</a>
                                    <small>(@ev.Date.ToString("dd.MM.yyyyг."))</small>
                                </h3>
                            </header>
                            <img src="@Url.Content(@ev.Banner)" alt="" class="alt major fa-area-chart" />
                            <p>@ev.Venue.City.Name @ev.Venue.Address</p>
                        </section>
                    }
                </div>
                <a asp-area="" asp-controller="Home" asp-action="Events" class="button">@loc["LearnMore"]</a>
            </div>
        </div>
        <h3><a href="#three" class="goto-next scrolly"></a></h3>
    </section>

    <section id="three" class="spotlight style3 bottom">
        <span class="image fit main"><img src="images/background1.jpg" alt="" /></span>
        <div class="content">
            <header >
                <h3>@loc["Tickets"]</h3>
                <p>@loc["TicketsDescription"]</p>
                <hr />
            </header>
            <header class="box alt">
                <div class="row uniform">
                    @foreach (Ticket t in Model.TopTickets)
                    {
                        <section class="4u 6u(medium) 12u$(xsmall)">
                            <header>
                                <h4>@t.Event.Name</h4>
                                <p>@t.Event.Venue.City.Name  @t.Event.Venue.Address</p>
                            </header>
                            <img src="@Url.Content(@t.Event.Banner)" alt="" class="alt major fa-area-chart" />

                            <ul class="alt">
                                <li><bold>@loc["Date"]</bold> @t.Event.Date.ToString("dd.MM.yyyy г.")</li>
                                <li><bold>@loc["Price"]</bold> @t.Price </li>
                                <li><bold>@loc["Seller"]</bold> @t.Seller.FirstName @t.Seller.LastName</li>
                            </ul>
                        </section>
                    }
                </div>
                <a asp-area="" asp-controller="Home" asp-action="Tickets" class="button">@loc["LearnMore"]</a>
            </header>
        </div>
    </section>

HelloTickets/HelloTickets/Views/Home/MyTickets.cshtml
@using HelloTickets.Models.Home
@inject IViewLocalizer loc
@model MyTicketsViewModel
@{
    ViewData["Title"] = loc["Title"];
}

    <section id="one" >
        <div class="content">
            <header class="major">
                <h2>@loc["MyTickets"] - @loc["Selling"]</h2>
            </header>
            <div class="table-wrapper">
                <table>
                    <thead>
                        <tr>
                            <th></th>
                            <th>@loc["EventName"]</th>
                            <th>@loc["CityAdress"]</th>
                            <th>@loc["Price"]</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Ticket t in Model.Selling)
                        {
                            <tr>
                                <td><img width="50" height="50" src="@Url.Content(@t.Event.Banner)" alt="" class="alt major fa-area-chart" /></td>
                                <td>@t.Event.Name</td>
                                <td>@t.Event.Venue.City.Name  @t.Event.Venue.Address</td>
                                <td>@t.Price $</td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>

        </div>
        <h3><a href="#two" class="goto-next scrolly"></a></h3>
    </section>

    <section id="two" >
        <div class="content">
            <header class="major">
                <h2>@loc["MyTickets"] - @loc["WaitingConfirmation"]</h2>
            </header>
            <div class="table-wrapper">
                <table>
                    <thead>
                        <tr>
                            <th></th>
                            <th>@loc["EventName"]</th>
                            <th>@loc["CityAdress"]</th>
                            <th>@loc["Price"]</th>
                            <th>@loc["Control"]</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (TicketOrderViewModel t in Model.WaitingConfirmation)
                        {
                            <tr>
                                <td><img width="50" height="50" src="@Url.Content(@t.Event.Banner)" alt="" class="alt major fa-area-chart" /></td>
                                <td>@t.Event.Name</td>
                                <td>@t.Event.Venue.City.Name  @t.Event.Venue.Address</td>
                                <td>@t.Price $</td>
                                <td>
                                    <a asp-area="" asp-controller="Trade" asp-route-status="@true" asp-route-Id="@t.OrderId" asp-action="Confirmation" class="button">@loc["Confirmation"]</a>
                                    <a asp-area="" asp-controller="Trade" asp-route-status="@false" asp-route-Id="@t.OrderId" asp-action="Confirmation" class="button">@loc["Rejected"]</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>

        </div>
        <h3><a href="#three" class="goto-next scrolly"></a></h3>
    </section>

    <section id="three" >
        <div class="content">
            <header class="major">
                <h2>@loc["MyTickets"] - @loc["Sold"]</h2>
            </header>
            <div class="table-wrapper">
                <table>
                    <thead>
                        <tr>
                            <th></th>
                            <th>@loc["EventName"]</th>
                            <th>@loc["CityAdress"]</th>
                            <th>@loc["Price"]</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Ticket t in Model.Sold)
                        {
                            <tr>
                                <td><img width="50" height="50" src="@Url.Content(@t.Event.Banner)" alt="" class="alt major fa-area-chart" /></td>
                                <td>@t.Event.Name</td>
                                <td>@t.Event.Venue.City.Name  @t.Event.Venue.Address</td>
                                <td>@t.Price $</td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
        </div>
    </section>

HelloTickets/HelloTickets/Views/Home/Tickets.cshtml
@using HelloTickets.Models.DataTemplate
@using HelloTickets.Models.Home
@model ATicketsViewModel
@inject IViewLocalizer loc
@{
    ViewData["Title"] = loc["Title"];
}

<div id="main" class="wrapper style1">
    <div class="container">
        <header class="major">
            <h2>@loc["Tickets"]</h2>
            <h3>@ViewData["NameEvents"]</h3>
            
        </header>
        <div class="row 150%">
            @foreach (TicketsViewModel t in Model.Tickets)
            {
                <section class="4u 6u(medium) 12u$(xsmall)">
                    <header>
                        <h4>@t.Event.Name</h4>
                        <p>@t.Event.Venue.City.Name  @t.Event.Venue.Address</p>
                    </header>
                    <img width="170" height="170" src="@Url.Content(@t.Event.Banner)" alt="" class="alt major fa-area-chart" />

                    <ul class="alt">
                        <li><bold>@loc["Date"]</bold> @t.Event.Date.ToString("dd.MM.yyyy г.")</li>
                        <li><bold>@loc["Price"]</bold> @t.Price </li>
                        <li><bold>@loc["Seller"]</bold> @t.Seller.FirstName @t.Seller.LastName 
                            @if (t.Seller.UserName == User.Identity.Name)
                            {
                                <code>@loc["Current"]</code>
                            }
                            else if(t.IsValid)
                            {
                                <a asp-area="" asp-controller="Trade" asp-route-ticketID="@t.Id" asp-action="Buy" class="button special">@loc["Buy"]</a>
                            }
                            else
                            {
                                <code>@loc["Order"]</code>
                            }
                        </li>
                    </ul>
                    <header />
                </section>
            }
        </div>
    </div>
</div>
@if(@Model.confirmation)
{
    <script>
        shownote({ html: '<n3>Билеты</n3><p>Заказ подтверждена</p>', className: 'message', time: 10000 });
    </script>
}

HelloTickets/HelloTickets/Views/Home/UserInfo.cshtml
@using HelloTickets.Models.Home
@inject IViewLocalizer loc
@model UserInfoViewModel 
@{
    ViewData["Title"] = @loc["Title"];
}

<div id="main" class="wrapper style1">
    <div class="container">
        <div class="row 150%">
            <h5>
                @loc["FirstName"]
            </h5>
            <p>@Model.FirstName</p>
        </div>
        <div class="row 150%">
            <h5>
                @loc["LastName"]
            </h5>
            <p>@Model.LastName</p>
        </div>
        <div class="row 150%">
            <h5>
                @loc["Localization"]
            </h5>
            <p>@Model.Localization</p>
        </div>
        <div class="row 150%">
            <h5>
                @loc["Email"]
            </h5>
            <p>@Model.Email</p>
        </div>
        <div class="row 150%">
            <h5>
                @loc["Address"]
            </h5>
            <p>@Model.Adress</p>
        </div>
        <div class="row 150%">
            <h5>
                @loc["PhoneNumber"]
            </h5>
            <p>@Model.PhoneNomber</p>
        </div>
        <div class="row 150%">
            <h3><a asp-area="" asp-route-idUser="@Model.Id" asp-controller="User" asp-action="EditCurrentUser"> @loc["Edit"] </a></h3>
        </div>    
    </div>
</div>