HelloTickets/HelloTickets/Models/DataControl/CityViewModel.cs
using HelloTickets.Models.DataTemplate;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HelloTickets.Models.DataControl
{
    public class CityViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "NameValue", ResourceType = typeof(Resources.Anotation))]
        [Remote(action: "VerifyCity", controller: "Validation")]
        public string Name { get; set; }
    }
}

HelloTickets/HelloTickets/Models/DataControl/DataListViewModel.cs
using HelloTickets.Models.DataTemplate;
using HelloTickets.Models.Tags;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloTickets.Models.DataControl
{
    public class DataListViewModel
    {
        public IEnumerable<City> Cities { get; set; }
        public PageViewModel PageCitiesViewModel { get; set; }

        public IEnumerable<Venue> Venues { get; set; }
        public PageViewModel PageVenueViewModel { get; set; }

        public IEnumerable<Event> Events { get; set; }
        public PageViewModel PageEventViewModel { get; set; }
    }
}

HelloTickets/HelloTickets/Models/DataControl/EventViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HelloTickets.Models.DataControl
{
    public class EventViewModel
    {
        public int Id { get; set; }
        [Required]
        [Remote(action: "VerifyEvent", controller: "Validation")]
        [Display(Name = "NameValue", ResourceType = typeof(Resources.Anotation))]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Date", ResourceType = typeof(Resources.Anotation))]
        public DateTime Date { get; set; }
        [Required]
        [Display(Name = "Banner", ResourceType = typeof(Resources.Anotation))]
        public string Banner { get; set; }
        [Required]
        [Display(Name = "Description", ResourceType = typeof(Resources.Anotation))]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Venue", ResourceType = typeof(Resources.Anotation))]
        public int VenueId { get; set; }

        public IEnumerable<SelectListItem> Venues { get; set; }
    }
}

HelloTickets/HelloTickets/Models/DataControl/VenueViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HelloTickets.Models.DataControl
{
    public class VenueViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "NameValue", ResourceType = typeof(Resources.Anotation))]
        [Remote(action: "VerifyVenue", controller: "Validation")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Address", ResourceType = typeof(Resources.Anotation))]
        public string Adres { get; set; }

        [Required]
        [Display(Name = "City", ResourceType = typeof(Resources.Anotation))]
        public int CityId { get; set; }

        public IEnumerable<SelectListItem> Cities { get; set; }
    }
}

HelloTickets/HelloTickets/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HelloTickets.Data;
using HelloTickets.Models.DataControl;

namespace HelloTickets.Controllers
{
    public class CityController : Controller
    {
        private CityDataLayer _cdata;

        public CityController(CityDataLayer cdata)
        {
            _cdata = cdata;
        }

        #region City
        [HttpGet]
        public IActionResult AddCity()
        {
            return View(new CityViewModel());
        }

        [HttpPost]
        public IActionResult AddCity(CityViewModel model)
        {
            if (ModelState.IsValid)
            {
                _cdata.AddCity(model.Name);
                return RedirectToAction("DataList", "DataControl");
            }
            else
                return View(model);
        }

        [HttpGet]
        public IActionResult EditCity(int id)
        {
            CityViewModel model = new CityViewModel();
            var a = _cdata.GetCityByID(id);
            model.Name = a.Name;
            model.Id = a.Id;
            return View(model);
        }

        [HttpPost]
        public IActionResult EditCity(int id, CityViewModel model)
        {
            _cdata.UpdateCity(id, model.Name);
            return RedirectToAction("DataList", "DataControl");
        }

        public IActionResult RemoveCity(int id)
        {
            _cdata.RemoveCity(id);
            return RedirectToAction("DataList", "DataControl");
        }
        #endregion
    }
}

HelloTickets/HelloTickets/Controllers/DataControlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using HelloTickets.Models.DataControl;
using HelloTickets.Data;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using HelloTickets.Models.Home;
using HelloTickets.Models.DataTemplate;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using HelloTickets.Models.Tags;

namespace HelloTickets.Controllers
{
    [Authorize]
    public class DataControlController : Controller
    {
        private CityDataLayer _cdata;
        private VenueDataLayer _vdata;
        private EventDataLayer _edata;

        private IHostingEnvironment AppEnvironment;

        public DataControlController(IHostingEnvironment appEnvironment,
            CityDataLayer cdata,
            VenueDataLayer vdata,
            EventDataLayer edata)
        {
            _cdata = cdata;
            _vdata = vdata;
            _edata = edata;
            AppEnvironment = appEnvironment;
        }

        public IActionResult DataList(int pageC = 1, int pageV = 1, int pageE = 1)
        {
            int pageSize = 5;
            DataListViewModel model = new DataListViewModel();

            var cities = _cdata.GetCities();
            var resC = cities.ToList().Skip((pageC - 1) * pageSize).Take(pageSize);
            PageViewModel pageCitiesViewModel = new PageViewModel(cities.Count(), pageC, pageSize);
            model.Cities = resC;
            model.PageCitiesViewModel = pageCitiesViewModel;

            var venue = _vdata.GetVenue(true);
            var resV = venue.ToList().Skip((pageV - 1) * pageSize).Take(pageSize);
            PageViewModel pageVenueViewModel = new PageViewModel(venue.Count(), pageV, pageSize);
            model.Venues = resV;
            model.PageVenueViewModel = pageVenueViewModel;

            var events = _edata.GetEvents(true);
            var resE = events.ToList().Skip((pageE - 1) * pageSize).Take(pageSize);
            PageViewModel pageEventViewModel = new PageViewModel(events.Count(), pageE, pageSize);
            model.Events = resE;
            model.PageEventViewModel = pageEventViewModel;
            return View(model);
        }
    }
}

HelloTickets/HelloTickets/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HelloTickets.Data;
using HelloTickets.Models.DataControl;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;

namespace HelloTickets.Controllers
{
    public class EventController : Controller
    {
        private EventDataLayer _edata;
        private VenueDataLayer _vdata;
        private IHostingEnvironment AppEnvironment;

        public EventController(EventDataLayer edata, 
            VenueDataLayer vdata,
            IHostingEnvironment appEnvironment)
        {
            _edata = edata;
            _vdata = vdata;
            AppEnvironment = appEnvironment;
        }

        #region Event
        [HttpGet]
        public IActionResult AddEvent()
        {
            EventViewModel model = new EventViewModel();
            model.Date = DateTime.Now;
            model.Venues = _vdata.GetVenueListItem();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddEvent(IFormFile uFile, EventViewModel model)
        {
            if (uFile == null)
            {
                return View(model);
            }

            string path = "/images/" + uFile.FileName;
            using (var fileStream = new FileStream(AppEnvironment.WebRootPath + path, FileMode.Create))
            {
                await uFile.CopyToAsync(fileStream);
            }
            model.Banner = path;
            _edata.AddEvent(model.Name, model.Date, model.Banner, model.Description, model.VenueId);
            var location = new Uri($"{Request.Scheme}://{Request.Host}/DataControl/DataList#three");
            return Redirect(location.ToString());
        }

        [HttpGet]
        public IActionResult EditEvent(int id)
        {
            EventViewModel model = new EventViewModel();
            var res = _edata.GetEventById(id, true);
            model.Name = res.Name;
            model.Banner = res.Banner;
            model.Date = res.Date;
            model.Description = res.Description;
            model.Id = res.Id;
            model.VenueId = res.VenueId;
            model.Venues = _vdata.GetVenueListItem();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditEvent(int id, IFormFile uFile, string LastBanner, EventViewModel model)
        {
            if (uFile != null)
            {
                string path = "/images/" + uFile.FileName;
                using (var fileStream = new FileStream(AppEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uFile.CopyToAsync(fileStream);
                }
                model.Banner = path;
            }
            else
            {
                model.Banner = LastBanner;
            }

            _edata.UpdateEvent(id, model.Name, model.Date, model.Banner, model.Description, model.VenueId);
            var location = new Uri($"{Request.Scheme}://{Request.Host}/DataControl/DataList#three");
            return Redirect(location.ToString());
        }

        public IActionResult RemoveEvent(int id)
        {
            _edata.RemoveEvent(id);
            var location = new Uri($"{Request.Scheme}://{Request.Host}/DataControl/DataList#three");
            return Redirect(location.ToString());
        }
        #endregion
    }
}

HelloTickets/HelloTickets/Views/DataControl/DataList.cshtml
@using HelloTickets.Models.Home
@using HelloTickets.Models.DataControl
@inject IViewLocalizer loc
@model DataListViewModel
@{
    ViewData["Title"] = loc["Title"];
}

@await Html.PartialAsync("PartialCity", @Model)

@await Html.PartialAsync("PartialVenue", @Model)

@await Html.PartialAsync("PartialEvent", @Model)

HelloTickets/HelloTickets/Views/DataControl/PartialCity.cshtml
@using HelloTickets.Models.DataControl
@inject IViewLocalizer loc
<section id="one" >
    <div class="content">
        <header class="major">
            <h2>@loc["Cities"]</h2>
        </header>
        <div class="table-wrapper fit">
            <table>
                <thead>
                    <tr>
                        <th>@loc["Name"]</th>
                        <th>@loc["Action"]</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (City c in Model.Cities)
                    {
                        <tr>
                            <td>@c.Name</td>
                            <td>
                                <span>
                                    <a class="button special" asp-route-id="@c.Id" asp-controller="City" asp-action="EditCity">@loc["Update"]</a>
                                    <a class="button special" asp-route-id="@c.Id" asp-controller="City" asp-action="RemoveCity">@loc["Delete"]</a>
                                </span>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                </tfoot>
            </table>
            <div class="row">
                <div class="6u 12u$(xsmall)">
                    <ul class="actions small">
                        @if (Model.PageCitiesViewModel.HasPreviousPage)
                        {
                        <li>
                            <a asp-controller="DataControl" asp-action="DataList"
                                asp-route-pageC="@(Model.PageCitiesViewModel.PageNumber - 1)"
                                class="button fit left">
                                <
                            </a>
                        </li>
                        }
                        @if(Model.PageCitiesViewModel.HasPreviousPage || Model.PageCitiesViewModel.HasNextPage)
                        {
                            <li><span>@Model.PageCitiesViewModel.PageNumber</span></li>
                        }

                        @if (Model.PageCitiesViewModel.HasNextPage)
                        {
                        <li>
                            <a asp-controller="DataControl" asp-action="DataList"
                                asp-route-pageC="@(Model.PageCitiesViewModel.PageNumber + 1)"
                                class="button fit left">
                                >
                            </a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
            <a class="button fit left" asp-controller="City" asp-action="AddCity">@loc["AddCity"]</a>
        </div>
    </div>
    <h3><a href="#two" class="goto-next scrolly"></a></h3>
</section>

HelloTickets/HelloTickets/Views/DataControl/PartialEvent.cshtml
@using HelloTickets.Models.DataControl
@inject IViewLocalizer loc
<section id="three" >
    <div class="content">
        <header class="major">
            <h2>@loc["Events"]</h2>
        </header>
        <div class="table-wrapper">
            <table>
                <thead>
                    <tr>
                        <th>@loc["Name"]</th>
                        <th>@loc["Date"]</th>
                        <th>@loc["Image"]</th>
                        <th>@loc["Description"]</th>
                        <th>@loc["Venue"]</th>
                        <th>@loc["Action"]</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Event e in Model.Events)
                    {
                        <tr>
                            <td>@e.Name</td>
                            <td>@e.Date.ToString("dd.MM.yyyy г.")</td>
                            <td><img width="50" height="50" src="@Url.Content(@e.Banner)" alt="" class="alt major fa-area-chart" /></td>
                            <td>@Html.Raw(e.Description)</td>
                            <td>@e.Venue.Name</td>
                            <td>
                                <span>
                                    <a class="button special" asp-route-id="@e.Id" asp-controller="Event" asp-action="EditEvent">@loc["Update"]</a>
                                    <a class="button special" asp-route-id="@e.Id" asp-controller="Event" asp-action="RemoveEvent">@loc["Delete"]</a>
                                </span>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                </tfoot>
            </table>
            <div class="row">
                <div class="6u 12u$(xsmall)">
                    <ul class="actions small">
                        @if (Model.PageEventViewModel.HasPreviousPage)
                        {
                            <li>
                                <a asp-controller="DataControl" asp-action="DataList"
                                   asp-route-pageE="@(Model.PageEventViewModel.PageNumber - 1)"
                                   asp-fragment="three"
                                   class="button fit left">
                                    <
                                </a>
                            </li>
                        }

                        @if(Model.PageEventViewModel.HasPreviousPage || Model.PageEventViewModel.HasNextPage)
                        {
                            <li><span>@Model.PageEventViewModel.PageNumber</span></li>
                        }

                        @if (Model.PageEventViewModel.HasNextPage)
                        {
                            <li>
                                <a asp-controller="DataControl" asp-action="DataList"
                                   asp-route-pageE="@(Model.PageEventViewModel.PageNumber + 1)"
                                   asp-fragment="three"
                                   class="button fit left">
                                    >
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <a class="button fit left" asp-controller="Event" asp-action="AddEvent">@loc["AddEvent"]</a>
        </div>
    </div>
</section>

HelloTickets/HelloTickets/Views/DataControl/PartialVenue.cshtml
@using HelloTickets.Models.DataControl
@inject IViewLocalizer loc

<section id="two" >
    <div class="content">
        <header class="major">
            <h2>@loc["Venue"]</h2>
        </header>
        <div class="table-wrapper">
            <table>
                <thead>
                    <tr>
                        <th>@loc["Name"]</th>
                        <th>@loc["Addres"]</th>
                        <th>@loc["City"]</th>
                        <th>@loc["Action"]</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Venue v in Model.Venues)
                    {
                        <tr>
                            <td>@v.Name</td>
                            <td>@v.Address</td>
                            <td>@v.City.Name</td>
                            <td>
                                <span>
                                    <a class="button special" asp-route-id="@v.Id" asp-controller="Venue" asp-action="EditVenue">@loc["Update"]</a>
                                    <a class="button special" asp-route-id="@v.Id" asp-controller="Venue" asp-action="RemoveVenue">@loc["Delete"]</a>
                                </span>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                </tfoot>
            </table>
            <div class="row">
                <div class="6u 12u$(xsmall)">
                    <ul class="actions small">
                        @if (Model.PageVenueViewModel.HasPreviousPage)
                        {
                            <li>
                                <a asp-controller="DataControl" asp-action="DataList"
                                   asp-route-pageV="@(Model.PageVenueViewModel.PageNumber - 1)"
                                   asp-fragment="two"
                                   class="button fit left">
                                    <
                                </a>
                            </li>
                        }

                        @if(Model.PageVenueViewModel.HasPreviousPage || Model.PageVenueViewModel.HasNextPage)
                        {
                            <li><h3>@Model.PageVenueViewModel.PageNumber</h3></li>
                        }

                        @if (Model.PageVenueViewModel.HasNextPage)
                        {
                            <li>
                                <a asp-controller="DataControl" asp-action="DataList"
                                   asp-route-pageV="@(Model.PageVenueViewModel.PageNumber + 1)"
                                   asp-fragment="two"
                                   class="button fit left">
                                    >
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <a class="button fit left" asp-controller="Venue" asp-action="AddVenue">@loc["AddVenue"]</a>
        </div>
    </div>
    <h3><a href="#three" class="goto-next scrolly"></a></h3>
</section>