HelloTickets/HelloTickets/Models/DataControl/VenueViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HelloTickets.Models.DataControl
{
    public class VenueViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "NameValue", ResourceType = typeof(Resources.Anotation))]
        [Remote(action: "VerifyVenue", controller: "Validation")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Address", ResourceType = typeof(Resources.Anotation))]
        public string Adres { get; set; }

        [Required]
        [Display(Name = "City", ResourceType = typeof(Resources.Anotation))]
        public int CityId { get; set; }

        public IEnumerable<SelectListItem> Cities { get; set; }
    }
}

HelloTickets/HelloTickets/Models/DataTemplate/Venue.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloTickets.Models.DataTemplate
{
    public class Venue
    {
        #region Fields
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public bool IsDelete { get; set; }

        public int CityId { get; set; }
        public City City { get; set; }
        #endregion
    }
}

HelloTickets/HelloTickets/Controllers/VenueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HelloTickets.Data;
using HelloTickets.Models.DataControl;

namespace HelloTickets.Controllers
{
    public class VenueController : Controller
    {
        private VenueDataLayer _vdata;
        private CityDataLayer _cdata;

        public VenueController(VenueDataLayer vdata, CityDataLayer cdata)
        {
            _vdata = vdata;
            _cdata = cdata;
        }

        #region Venue
        [HttpGet]
        public IActionResult AddVenue()
        {
            VenueViewModel model = new VenueViewModel();
            model.Cities = _cdata.GetCitiesListItem();
            return View(model);
        }

        [HttpPost]
        public IActionResult AddVenue(VenueViewModel model)
        {
            _vdata.AddVenue(model.Name, model.Adres, model.CityId);
            var location = new Uri($"{Request.Scheme}://{Request.Host}/DataControl/DataList#two");
            return Redirect(location.ToString());
        }

        [HttpGet]
        public IActionResult EditVenue(int id)
        {
            var res = _vdata.GetVenueById(id, true);
            VenueViewModel model = new VenueViewModel();
            model.Adres = res.Address;
            model.CityId = res.CityId;
            model.Name = res.Name;
            model.Cities = _cdata.GetCitiesListItem();
            return View(model);
        }

        [HttpPost]
        public IActionResult EditVenue(int id, VenueViewModel model)
        {
            _vdata.UpdateVenue(id, model.Name, model.Adres, model.CityId);
            var location = new Uri($"{Request.Scheme}://{Request.Host}/DataControl/DataList#two");
            return Redirect(location.ToString());
        }

        public IActionResult RemoveVenue(int id)
        {
            _vdata.RemoveVenue(id);
            //придумать как передовать специальные аргументы
            var location = new Uri($"{Request.Scheme}://{Request.Host}/DataControl/DataList#two");
            return Redirect(location.ToString());
        }
        #endregion
    }
}

HelloTickets/HelloTickets/Views/Venue/AddVenue.cshtml
@using HelloTickets.Models.DataControl
@inject IViewLocalizer loc
@model VenueViewModel
@{
    ViewData["Title"] = @loc["Title"];
}

<div id="main" class="wrapper style1">
    <div class="container">
        <header class="major">
            <h2>@loc["Title"]</h2>
        </header>
        <div class="row 150%">
            <div class="table-wrapper">
                <form asp-controller="Venue" asp-action="AddVenue" method="post" class="form-horizontal">
                    <h3>@loc["Info"]</h3>
                    <hr />
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <p></p>
                        <label asp-for="Name" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <p></p>
                        <label asp-for="Adres" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="Adres" class="form-control" />
                            <span asp-validation-for="Adres" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <p></p>
                        <label asp-for="CityId" class="col-md-2 control-label"></label>
                        <div class="select-wrapper">
                            <select asp-for="CityId" asp-items="@Model.Cities" id="category">
                                <option value="">- City -</option>
                            </select>
                        </div>
                    </div>

                    <div>
                        <div>
                            <button class="button special" type="submit">@loc["Add"]</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

HelloTickets/HelloTickets/Views/Venue/EditVenue.cshtml
@using HelloTickets.Models.DataControl
@inject IViewLocalizer loc
@model VenueViewModel
@{
    ViewData["Title"] = @loc["Title"];
}

<div id="main" class="wrapper style1">
    <div class="container">
        <header class="major">
            <h2>@loc["Title"]</h2>
        </header>
        <div class="row 150%">
            <div class="table-wrapper">
                <form asp-controller="Venue" asp-action="EditVenue" method="post" class="form-horizontal">
                    <h3>@loc["Info"]</h3>
                    <hr />
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <p></p>
                        <label asp-for="Name" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <p></p>
                        <label asp-for="Adres" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="Adres" class="form-control" />
                            <span asp-validation-for="Adres" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <p></p>
                        <label asp-for="CityId" class="col-md-2 control-label"></label>
                        <div class="select-wrapper">
                            <select asp-for="CityId" asp-items="@Model.Cities" id="category">
                                <option value="">- City -</option>
                            </select>
                        </div>
                    </div>

                    <div>
                        <div>
                            <button class="button special" type="submit">@loc["Update"]</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>