HelloTickets/HelloTickets/Controllers/DataControlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using HelloTickets.Models.DataControl;
using HelloTickets.Data;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using HelloTickets.Models.Home;
using HelloTickets.Models.DataTemplate;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using HelloTickets.Models.Tags;

namespace HelloTickets.Controllers
{
    [Authorize]
    public class DataControlController : Controller
    {
        private CityDataLayer _cdata;
        private VenueDataLayer _vdata;
        private EventDataLayer _edata;

        private IHostingEnvironment AppEnvironment;

        public DataControlController(IHostingEnvironment appEnvironment,
            CityDataLayer cdata,
            VenueDataLayer vdata,
            EventDataLayer edata)
        {
            _cdata = cdata;
            _vdata = vdata;
            _edata = edata;
            AppEnvironment = appEnvironment;
        }

        public IActionResult DataList(int pageC = 1, int pageV = 1, int pageE = 1)
        {
            int pageSize = 5;
            DataListViewModel model = new DataListViewModel();

            var cities = _cdata.GetCities();
            var resC = cities.ToList().Skip((pageC - 1) * pageSize).Take(pageSize);
            PageViewModel pageCitiesViewModel = new PageViewModel(cities.Count(), pageC, pageSize);
            model.Cities = resC;
            model.PageCitiesViewModel = pageCitiesViewModel;

            var venue = _vdata.GetVenue(true);
            var resV = venue.ToList().Skip((pageV - 1) * pageSize).Take(pageSize);
            PageViewModel pageVenueViewModel = new PageViewModel(venue.Count(), pageV, pageSize);
            model.Venues = resV;
            model.PageVenueViewModel = pageVenueViewModel;

            var events = _edata.GetEvents(true);
            var resE = events.ToList().Skip((pageE - 1) * pageSize).Take(pageSize);
            PageViewModel pageEventViewModel = new PageViewModel(events.Count(), pageE, pageSize);
            model.Events = resE;
            model.PageEventViewModel = pageEventViewModel;
            return View(model);
        }
    }
}

HelloTickets/HelloTickets/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HelloTickets.Data;
using HelloTickets.Models.Home;
using HelloTickets.Models.DataTemplate;
using System.Security.Claims;

namespace HelloTickets.Controllers
{
    public class TicketController : Controller
    {
        private TicketDataLayer _tdata;
        private EventDataLayer _edata;

        public TicketController(TicketDataLayer tdata, EventDataLayer edata)
        {
            _tdata = tdata;
            _edata = edata;
        }

        #region Ticket
        [HttpGet]
        public IActionResult AddTicket()
        {
            AddTicketViewModel model = new AddTicketViewModel();
            model.Events = _edata.GetEventsListItem();
            return View(model);
        }

        [HttpPost]
        public IActionResult AddTicket(AddTicketViewModel model)
        {
            if (ModelState.IsValid)
            {
                string userId = User.Claims.First((x) => x.Type == ClaimTypes.NameIdentifier).Value;
                _tdata.AddTicket(new Ticket { EventId = model.EventId, Price = model.Price, SellerId = userId });
                return RedirectToAction("Tickets", "Home");
            }
            else
            {
                model.Events = _edata.GetEventsListItem();
                return View(model);
            }
        }
        #endregion
    }
}

HelloTickets/HelloTickets/Controllers/UserController.cs
using HelloTickets.Data;
using HelloTickets.Models.DataTemplate;
using HelloTickets.Models.Home;
using HelloTickets.Models.Manage;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloTickets.Controllers
{
    [Authorize]
    public class UserController: Controller
    {
        private UserDataLayer _udata;
        private RoleDataLayer _rdata;
        private readonly SignInManager<User> SignInManager;

        public UserController(
            UserDataLayer udata,
            RoleDataLayer rdata,
            SignInManager<User> signInManager)
        {
            _udata = udata;
            _rdata = rdata;
            SignInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Users()
        {
            List<UserListViewModel> model = new List<UserListViewModel>();
            var us = _udata.GetUsers();
            model = us.Select(u => new UserListViewModel
                                        {
                                            Id = u.Id,
                                            Name = u.UserName,
                                            Email = u.Email,
                                            RoleName = _rdata.GetFirstRoleNameByUser(u)
                                        }).Where((X) => X.RoleName != "super").ToList();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string idUser)
        {
            User u = await _udata.GetUserByIdAsync(idUser);
            UserViewModel model = new UserViewModel()
                                        {
                                            Email = u.Email,
                                            Id = idUser,
                                            Name = u.UserName,
                                            RoleId = _rdata.GetRoleIdToUser(u),
                                            Roles = _rdata.GetAllRoles()
                                        };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditUser(string idUser, UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Id = idUser;
                var result = _udata.UpdateUserAsync(model);
                if(result.Result.Succeeded)
                    return RedirectToAction("Users");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditCurrentUser()
        {
            User u = await _udata.GetUserByNameAsync(User.Identity.Name);
            UserInfoViewModel model = new UserInfoViewModel();
            model.Id = u.Id;
            model.FirstName = u.FirstName;
            model.Email = u.Email;
            model.Localization = u.Localization;
            model.LastName = u.LastName;
            model.Adress = u.Address;
            model.PhoneNomber = u.PhoneNumber;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCurrentUser(string id, UserInfoViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Id = id;
                var result = _udata.UpdateCurrentUserAsync(model);
                if (result.Result.Succeeded)
                {
                    User u = await _udata.GetUserByIdAsync(model.Id);
                    await SignInManager.RefreshSignInAsync(u);
                    Response.Cookies.Append(
                        CookieRequestCultureProvider.DefaultCookieName,
                        CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(model.Localization)),
                        new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
);
                    return RedirectToAction(nameof(HomeController.UserInfo), "Home");
                }

                return View(model);
            }

            return View(model);
        }
    }
}

HelloTickets/HelloTickets/Views/Shared/Layout.cshtml
@inject IViewLocalizer loc
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"] - HelloTickets</title>
    <link rel="stylesheet" href="~/assets/css/main.css" />
    <link rel="stylesheet" href="~/assets/css/Notes.css" />
</head>
<body class="landing">
    <div class="notification"><ul id="NotifyPanel" ></ul> </div>
    <script src="~/assets/js/Notes.js"></script>
    <div id="page-wrapper">
        <header id="header" class="Color">
            <h1 id="logo"><a asp-area="" asp-controller="Home" asp-action="Index" >@loc["HelloTickets"]</a></h1>
            <nav id="nav">
                <ul>
                    <li><b><a href="~/TestPage.html"> -=API=- </a></b></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">@loc["Home"]</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Events">@loc["Events"]</a></li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Tickets">@loc["Tickets"]</a>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <ul>
                                <li><a asp-area="" asp-controller="Home" asp-action="MyTickets">@loc["Mytickets"]</a></li>
                                <li><a asp-area="" asp-controller="Home" asp-action="Myorders">@loc["Myorders"]</a></li>
                                <li><a asp-area="" asp-controller="Ticket" asp-action="AddTicket">@loc["AddTicket"]</a></li>
                            </ul>
                        }
                    </li>
                    @await Html.PartialAsync("LoginPartial")
                </ul>
            </nav>
        </header>

        @RenderBody();

        <footer id="footer">
            <nav id="nav">
                <ul class="nav">
                    <li><b><a href="~/TestPage.html"> -=API=- </a></b></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">@loc["Home"]</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Events">@loc["Events"]</a></li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Tickets">@loc["Tickets"]</a>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <ul>
                                <li><a asp-area="" asp-controller="Home" asp-action="MyTickets">@loc["Mytickets"]</a></li>
                                <li><a asp-area="" asp-controller="Home" asp-action="Myorders">@loc["Myorders"]</a></li>
                                <li><a asp-area="" asp-controller="DataControl" asp-action="AddTicket">@loc["AddTicket"]</a></li>
                            </ul>
                        }
                    </li>
                    @await Html.PartialAsync("LoginPartial")
                </ul>
                <ul class="copyright">
                    <li>@await Html.PartialAsync("Viewlocal")</li>
                </ul>
            </nav>
    </footer>
    </div>

    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/jquery.scrolly.min.js"></script>
    <script src="~/assets/js/jquery.dropotron.min.js"></script>
    <script src="~/assets/js/jquery.scrollex.min.js"></script>
    <script src="~/assets/js/skel.min.js"></script>
    <script src="~/assets/js/util.js"></script>
    <script src="~/assets/js/main.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.11.3.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

HelloTickets/HelloTickets/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using HelloTickets.Models.DataTemplate;
@using System.Security.Claims;

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@inject IViewLocalizer loc

@if (SignInManager.IsSignedIn(User))
{
    <li>
        <h5>
            <a asp-area="" asp-controller="Home" asp-action="UserInfo">@loc["Hello"] @UserManager.GetUserName(User)!</a>
        </h5>
        @if (User.Claims.First((x) => x.Type == ClaimTypes.Role) != null &&
            (User.Claims.FirstOrDefault((x) => x.Type == ClaimTypes.Role).Value == "admin" ||
            User.Claims.FirstOrDefault((x) => x.Type == ClaimTypes.Role).Value == "sadmin"))
        {
            <ul>
                <li><a asp-area="" asp-controller="User" asp-action="Users">@loc["Users"]</a></li>
                <li><a asp-area="" asp-controller="DataControl" asp-action="DataList">@loc["Data"]</a></li>
            </ul>
        }
    </li>
    <li>
        <a asp-controller="Account" asp-action="Logout" class="button small special">@loc["Logout"]</a>
    </li>
}
else
{
    <li><a asp-area="" asp-controller="Account" asp-action="Login" class="button small">@loc["Login"]</a></li>
}

HelloTickets/HelloTickets/Views/Shared/Viewlocal.cshtml
@using Microsoft.AspNetCore.Builder

@using Microsoft.Extensions.Options

@inject IViewLocalizer loc
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div title="@requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home"
          asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
          method="post" class="form-horizontal" role="form">
        @loc["Language"] <select name="culture"
                                       onchange="this.form.submit();"
                                       asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
    </form>
</div>